name: Verify Pull Request

on: [ pull_request, workflow_dispatch ]

jobs:
  check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/gradle-cache
      - name: Check app
        run: ./gradlew check

  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/gradle-cache
      - name: Run tests
        run: ./gradlew test
